### ISSUE TITLE
Is UnixStickers.com still active ?

### ISSUE THREAD

**Issue by shulard** [hoaproject/Blog#16]
Hello,

I've checked on old articles and found that the UnixStickers.com images are not loading anymore, also on the [meta store page](https://www.hoa-project.com/).

Example: https://blog.hoa-project.net/2015/11-1-million-installations-and-a-meta-shop.html

Maybe we need to drop references to these ?

**Comment by Hywan** [comment]
UnixStickers is no longer a sponsor, so we can even remove them from the homepage :-p. Ready for a PR ;-)?

**Comment by shulard** [comment]
This was handled by #17.
